-- Times do Brasileirao
INSERT INTO `equipe` (`equipe_id`, `nome_equipe`, `url_logo_equipe`) VALUES
(1, 'Atletico-GO', 'https://ssl.gstatic.com/onebox/media/sports/logos/9V6l9h3cJVQ0lqqX6-57zQ_96x96.png'),
(2, 'Atletico-MG', 'https://ssl.gstatic.com/onebox/media/sports/logos/q9fhEsgpuyRq58OgmSndcQ_96x96.png'),
(3, 'Athletico-PR', 'https://ssl.gstatic.com/onebox/media/sports/logos/LtpA9v-CQ_Qs2bgWVdDXxQ_96x96.png'),
(4, 'Bahia', 'https://ssl.gstatic.com/onebox/media/sports/logos/nIdbR6qIUDyZUBO9vojSPw_96x96.png'),
(5, 'Botafogo', 'https://ssl.gstatic.com/onebox/media/sports/logos/KLDWYp-H8CAOT9H_JgizRg_96x96.png'),
(6, 'Ceara', 'https://ssl.gstatic.com/onebox/media/sports/logos/mSl0cz3i2t8uv4zcprobOg_96x96.png'),
(7, 'Corinthians', 'https://ssl.gstatic.com/onebox/media/sports/logos/tCMSqgXVHROpdCpQhzTo1g_96x96.png'),
(8, 'Coritiba', 'https://ssl.gstatic.com/onebox/media/sports/logos/LaFlBADLmsjHfGTehCYtuA_96x96.png'),
(9, 'Cruzeiro', 'https://ssl.gstatic.com/onebox/media/sports/logos/LK-rYXprWOKfSP5BYAy-lQ_96x96.png'),
(10, 'Cuiaba', 'https://ssl.gstatic.com/onebox/media/sports/logos/XyKo3bgk7ToHrmBR1Oiulw_96x96.png'),
(11, 'Flamengo', 'https://ssl.gstatic.com/onebox/media/sports/logos/orE554NToSkH6nuwofe7Yg_96x96.png'),
(12, 'Fluminense', 'https://ssl.gstatic.com/onebox/media/sports/logos/fCMxMMDF2AZPU7LzYKSlig_96x96.png'),
(13, 'Fortaleza', 'https://ssl.gstatic.com/onebox/media/sports/logos/me10ephzRxdj45zVq1Risg_96x96.png'),
(14, 'Goias', 'https://ssl.gstatic.com/onebox/media/sports/logos/gb8bo2x00XsbvsVp9nGniA_96x96.png'),
(15, 'Gremio', 'https://ssl.gstatic.com/onebox/media/sports/logos/Ku-73v_TW9kpex-IEGb0ZA_96x96.png'),
(16, 'Internacional', 'https://ssl.gstatic.com/onebox/media/sports/logos/OWVFKuHrQuf4q2Wk0hEmSA_96x96.png'),
(17, 'Palmeiras', 'https://ssl.gstatic.com/onebox/media/sports/logos/7spurne-xDt2p6C0imYYNA_96x96.png'),
(18, 'RB Bragantino', 'https://ssl.gstatic.com/onebox/media/sports/logos/KR_KUEAw5NGP0npb2dOpig_96x96.png'),
(19, 'Santos', 'https://ssl.gstatic.com/onebox/media/sports/logos/VHdNOT6wWOw_vJ38GMjMzg_96x96.png'),
(20, 'Sao Paulo', 'https://ssl.gstatic.com/onebox/media/sports/logos/4w2Z97Hf9CSOqICK3a8AxQ_96x96.png'),
(21, 'Vasco da Gama', 'https://ssl.gstatic.com/onebox/media/sports/logos/_4RUqwd5euAxf0MtbPwq4A_96x96.png');

-- Selecoes da Copa do Mundo (Classificadas 2026)
INSERT INTO `equipe` (`equipe_id`, `nome_equipe`, `url_logo_equipe`) VALUES
(101, 'Brasil', 'https://ssl.gstatic.com/onebox/media/sports/logos/Fh5RjHTXyFB-7qJofS4fAA_96x96.png'),
(102, 'Argentina', 'https://ssl.gstatic.com/onebox/media/sports/logos/9sI8qYpG3WGxV-4T1Nn8Rw_96x96.png'),
(103, 'Franca', 'https://ssl.gstatic.com/onebox/media/sports/logos/sMkG8pBcImsV4MF-0Zn8Rw_96x96.png'),
(104, 'Espanha', 'https://ssl.gstatic.com/onebox/media/sports/logos/KYlBhMXjT0WvPthU0H0R0w_96x96.png'),
(105, 'Inglaterra', 'https://ssl.gstatic.com/onebox/media/sports/logos/8jKBN3VpMfh1BJeXo_Ln8Rw_96x96.png'),
(106, 'Alemanha', 'https://ssl.gstatic.com/onebox/media/sports/logos/r0b9r7jHvdgVdLqK-e-8Rw_96x96.png'),
(107, 'Portugal', 'https://ssl.gstatic.com/onebox/media/sports/logos/XIhQsWk3KqYB-3f1Nn8Rw_96x96.png'),
(108, 'Italia', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(109, 'Holanda', 'https://ssl.gstatic.com/onebox/media/sports/logos/Fh5RjHTXyFB-7qJofS4fAA_96x96.png'),
(110, 'Belgica', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(111, 'Croacia', 'https://ssl.gstatic.com/onebox/media/sports/logos/r0b9r7jHvdgVdLqK-e-8Rw_96x96.png'),
(112, 'Marrocos', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(113, 'Japao', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(114, 'Coreia do Sul', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(115, 'Australia', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(116, 'Mexico', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(117, 'Estados Unidos', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(118, 'Canada', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(119, 'Uruguai', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(120, 'Colombia', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(121, 'Equador', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(122, 'Senegal', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(123, 'Tunisia', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(124, 'Gana', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(125, 'Camaroes', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(126, 'Nigeria', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(127, 'Costa Rica', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(128, 'Panama', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(129, 'Arabia Saudita', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(130, 'Ira', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(131, 'Qatar', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(132, 'Emirados Arabes', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(133, 'China', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(134, 'India', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(135, 'Grecia', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(136, 'Servia', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(137, 'Polonia', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(138, 'Ucrania', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(139, 'Dinamarca', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(140, 'Suecia', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(141, 'Noruega', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(142, 'Suica', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(143, 'Austria', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(144, 'Republica Tcheca', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(145, 'Escocia', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(146, 'Pais de Gales', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(147, 'Irlanda do Norte', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(148, 'Turquia', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(149, 'Israel', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png'),
(150, 'Nova Zelandia', 'https://ssl.gstatic.com/onebox/media/sports/logos/2Hv_T7JQj7dVdLqK-e-8Rw_96x96.png');
